// Mock useLanguage hook for demonstration

export const translations = {
  en: {
    shop: 'Book Shop',
    searchBooks: 'Search books...',
    addToCart: 'Add to Cart',
    orderNow: 'Order Now',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    filter: 'Filter',
    allCategories: 'All Categories',
    cart: 'Cart',
    total: 'Total',
    checkout: 'Checkout',
    orderSuccess: 'Order placed successfully!',
    pages: 'pages',
    published: 'Published',
    category: 'Category',
    author: 'Author',
    rating: 'Rating',
    reviews: 'reviews',
    addedToCart: 'Added to cart!',
    cartEmpty: 'Your cart is empty',
    continueReading: 'Continue your reading journey',
    featuredBooks: 'Featured Books',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    viewDetails: 'View Details',
    quickView: 'Quick View',
    wishlist: 'Add to Wishlist',
    removeFromCart: 'Remove from cart',
    proceedToCheckout: 'Proceed to Checkout',
    backToShopping: 'Back to Shopping',
    orderTotal: 'Order Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free'
  },
  sw: {
    shop: 'Duka la Vitabu',
    searchBooks: 'Tafuta vitabu...',
    addToCart: 'Ongeza kwenye Mkoba',
    orderNow: 'Agiza Sasa',
    price: 'Bei',
    inStock: 'Ipo Dukani',
    outOfStock: 'Haipatikani',
    quantity: 'Idadi',
    filter: 'Chuja',
    allCategories: 'Makundi Yote',
    cart: 'Mkoba',
    total: 'Jumla',
    checkout: 'Maliza Ununuzi',
    orderSuccess: 'Agizo limefanikiwa!',
    pages: 'kurasa',
    published: 'Ilichapishwa',
    category: 'Kundi',
    author: 'Mwandishi',
    rating: 'Kiwango',
    reviews: 'maoni',
    addedToCart: 'Imeongezwa kwenye mkoba!',
    cartEmpty: 'Mkoba wako hauina kitu',
    continueReading: 'Endelea na safari yako ya kusoma',
    featuredBooks: 'Vitabu Maalum',
    newArrivals: 'Vitabu Vipya',
    bestsellers: 'Vitabu Vyenye Kuuzwa Zaidi',
    viewDetails: 'Ona Maelezo',
    quickView: 'Ona Haraka',
    wishlist: 'Ongeza kwenye Orodha ya Hamu',
    removeFromCart: 'Ondoa kutoka mkobani',
    proceedToCheckout: 'Endelea na Malipo',
    backToShopping: 'Rudi Ununuzi',
    orderTotal: 'Jumla ya Agizo',
    subtotal: 'Jumla Ndogo',
    shipping: 'Usafirishaji',
    free: 'Bure'
  }
};

// Enhanced sample books data with Chris Mauki's relationship and marriage focus
export const sampleBooks = [
  {
    id: 1,
    title: "Mahusiano ya Dhati",
    author: "Chris Mauki",
    category: "Mahusiano",
    price: 35000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 187,
    pages: 280,
    publishedYear: 2023,
    inStock: true,
    stockCount: 12,
    description: "Mwongozo kamili wa kujenga mahusiano ya dhati na endelevu katika maisha yako.",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 2,
    title: "Ndoa Yenye Furaha",
    author: "Chris Mauki",
    category: "Ndoa",
    price: 40000,
    originalPrice: 50000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 234,
    pages: 320,
    publishedYear: 2024,
    inStock: true,
    stockCount: 8,
    description: "Siri za kujenga ndoa yenye furaha, amani na mapenzi yasiyoisha.",
    featured: true,
    bestseller: true,
    newArrival: true
  },
  {
    id: 3,
    title: "Mapenzi Halisi",
    author: "Chris Mauki",
    category: "Mapenzi",
    price: 28000,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 156,
    pages: 245,
    publishedYear: 2023,
    inStock: true,
    stockCount: 18,
    description: "Jinsi ya kutofautisha mapenzi ya dhati na yale ya uongo katika mahusiano.",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 4,
    title: "Utayarishaji wa Ndoa",
    author: "Chris Mauki",
    category: "Ndoa",
    price: 32000,
    originalPrice: 38000,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 198,
    pages: 290,
    publishedYear: 2022,
    inStock: true,
    stockCount: 15,
    description: "Hatua muhimu za kutayarisha ndoa yenye msingi imara na malengo ya pamoja.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 5,
    title: "Mawasiliano Katika Ndoa",
    author: "Chris Mauki",
    category: "Mawasiliano",
    price: 26000,
    originalPrice: 32000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 143,
    pages: 220,
    publishedYear: 2024,
    inStock: true,
    stockCount: 20,
    description: "Mbinu za kuongea, kusikiliza na kutatua matatizo katika ndoa kwa hekima.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 6,
    title: "Kusamehe na Kuendelea",
    author: "Chris Mauki",
    category: "Msamaha",
    price: 24000,
    originalPrice: 30000,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 167,
    pages: 200,
    publishedYear: 2023,
    inStock: true,
    stockCount: 22,
    description: "Jinsi ya kusamehe makosa na kujenga upya mahusiano baada ya uchungu.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 7,
    title: "Heshima Katika Mahusiano",
    author: "Chris Mauki",
    category: "Heshima",
    price: 30000,
    originalPrice: 36000,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 125,
    pages: 260,
    publishedYear: 2024,
    inStock: false,
    stockCount: 0,
    description: "Umuhimu wa heshima ya kila mmoja katika kujenga mahusiano imara.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 8,
    title: "Kupenda Bila Masharti",
    author: "Chris Mauki",
    category: "Upendo",
    price: 25000,
    originalPrice: 31000,
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    rating: 4.5,
    reviews: 134,
    pages: 210,
    publishedYear: 2023,
    inStock: true,
    stockCount: 16,
    description: "Mafundisho ya jinsi ya kupenda bila kujitenga au kutaka kubadilisha mtu.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 9,
    title: "Familia Yenye Amani",
    author: "Chris Mauki",
    category: "Familia",
    price: 28000,
    originalPrice: 34000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 89,
    pages: 275,
    publishedYear: 2022,
    inStock: true,
    stockCount: 14,
    description: "Jinsi ya kuongoza familia na kujenga mazingira ya amani na upendo nyumbani.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 10,
    title: "Kuokoa Ndoa Yako",
    author: "Chris Mauki",
    category: "Uokozi wa Ndoa",
    price: 38000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 211,
    pages: 340,
    publishedYear: 2024,
    inStock: true,
    stockCount: 9,
    description: "Mbinu za kurekebisha na kuokoa ndoa zilizopotea moto wa mapenzi.",
    featured: true,
    bestseller: true,
    newArrival: true
  }
];