// Mock useLanguage hook for demonstration

export const translations = {
  en: {
    shop: 'Book Shop',
    searchBooks: 'Search books...',
    addToCart: 'Add to Cart',
    orderNow: 'Order Now',
    price: 'Price',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    quantity: 'Quantity',
    filter: 'Filter',
    allCategories: 'All Categories',
    cart: 'Cart',
    total: 'Total',
    checkout: 'Checkout',
    orderSuccess: 'Order placed successfully!',
    pages: 'pages',
    published: 'Published',
    category: 'Category',
    author: 'Author',
    rating: 'Rating',
    reviews: 'reviews',
    addedToCart: 'Added to cart!',
    cartEmpty: 'Your cart is empty',
    continueReading: 'Continue your reading journey',
    featuredBooks: 'Featured Books',
    newArrivals: 'New Arrivals',
    bestsellers: 'Bestsellers',
    viewDetails: 'View Details',
    quickView: 'Quick View',
    wishlist: 'Add to Wishlist',
    removeFromCart: 'Remove from cart',
    proceedToCheckout: 'Proceed to Checkout',
    backToShopping: 'Back to Shopping',
    orderTotal: 'Order Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    free: 'Free'
  },
  sw: {
    shop: 'Duka la Vitabu',
    searchBooks: 'Tafuta vitabu...',
    addToCart: 'Ongeza kwenye Mkoba',
    orderNow: 'Agiza Sasa',
    price: 'Bei',
    inStock: 'Ipo Dukani',
    outOfStock: 'Haipatikani',
    quantity: 'Idadi',
    filter: 'Chuja',
    allCategories: 'Makundi Yote',
    cart: 'Mkoba',
    total: 'Jumla',
    checkout: 'Maliza Ununuzi',
    orderSuccess: 'Agizo limefanikiwa!',
    pages: 'kurasa',
    published: 'Ilichapishwa',
    category: 'Kundi',
    author: 'Mwandishi',
    rating: 'Kiwango',
    reviews: 'maoni',
    addedToCart: 'Imeongezwa kwenye mkoba!',
    cartEmpty: 'Mkoba wako hauina kitu',
    continueReading: 'Endelea na safari yako ya kusoma',
    featuredBooks: 'Vitabu Maalum',
    newArrivals: 'Vitabu Vipya',
    bestsellers: 'Vitabu Vyenye Kuuzwa Zaidi',
    viewDetails: 'Ona Maelezo',
    quickView: 'Ona Haraka',
    wishlist: 'Ongeza kwenye Orodha ya Hamu',
    removeFromCart: 'Ondoa kutoka mkobani',
    proceedToCheckout: 'Endelea na Malipo',
    backToShopping: 'Rudi Ununuzi',
    orderTotal: 'Jumla ya Agizo',
    subtotal: 'Jumla Ndogo',
    shipping: 'Usafirishaji',
    free: 'Bure'
  }
};

// Enhanced sample books data with Chris Mauki's relationship and marriage focus
export const sampleBooks = [
  {
    id: 1,
    title: "Ujasiriamali wa Dhati",
    author: "Emmanuel Akyoo",
    category: "Ujasiriamali",
    price: 35000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 187,
    pages: 280,
    publishedYear: 2023,
    inStock: true,
    stockCount: 12,
    description: "Mwongozo kamili wa kujenga biashara yenye mafanikio kutoka msingi hadi ukuaji.",
    featured: true,
    bestseller: true,
    newArrival: false
  },
  {
    id: 2,
    title: "Maisha Yenye Lengo",
    author: "Emmanuel Akyoo",
    category: "Maendeleo ya Kibinafsi",
    price: 40000,
    originalPrice: 50000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 234,
    pages: 320,
    publishedYear: 2024,
    inStock: true,
    stockCount: 8,
    description: "Siri za kujenga maisha yenye maana, mafanikio na furaha ya kudumu.",
    featured: true,
    bestseller: true,
    newArrival: true
  },
  {
    id: 3,
    title: "Motisha ya Kila Siku",
    author: "Emmanuel Akyoo",
    category: "Motisha",
    price: 28000,
    originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 156,
    pages: 245,
    publishedYear: 2023,
    inStock: true,
    stockCount: 18,
    description: "Jinsi ya kudumisha motisha na kuzidi kuendelea mbele hata wakati wa changamoto.",
    featured: false,
    bestseller: true,
    newArrival: false
  },
  {
    id: 4,
    title: "Kujenga Utajiri",
    author: "Emmanuel Akyoo",
    category: "Fedha",
    price: 32000,
    originalPrice: 38000,
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 198,
    pages: 290,
    publishedYear: 2022,
    inStock: true,
    stockCount: 15,
    description: "Hatua muhimu za kujenga utajiri wa kudumu na uhuru wa kifedha.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 5,
    title: "Uongozi wa Kizazi Kipya",
    author: "Emmanuel Akyoo",
    category: "Uongozi",
    price: 26000,
    originalPrice: 32000,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 143,
    pages: 220,
    publishedYear: 2024,
    inStock: true,
    stockCount: 20,
    description: "Mbinu za uongozi wa kisasa kwa vijana na waongoza wa kizazi kipya.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 6,
    title: "Kushinda Changamoto",
    author: "Emmanuel Akyoo",
    category: "Changamoto",
    price: 24000,
    originalPrice: 30000,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400&h=600&fit=crop",
    rating: 4.8,
    reviews: 167,
    pages: 200,
    publishedYear: 2023,
    inStock: true,
    stockCount: 22,
    description: "Jinsi ya kushinda changamoto na kubadilisha vikwazo kuwa fursa za mafanikio.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 7,
    title: "Digital Marketing Mastery",
    author: "Emmanuel Akyoo",
    category: "Teknolojia",
    price: 30000,
    originalPrice: 36000,
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=600&fit=crop",
    rating: 4.7,
    reviews: 125,
    pages: 260,
    publishedYear: 2024,
    inStock: false,
    stockCount: 0,
    description: "Mwongozo kamili wa kutumia mitandao ya kijamii na teknolojia kuongeza biashara.",
    featured: false,
    bestseller: true,
    newArrival: true
  },
  {
    id: 8,
    title: "Mzazi Mjasiriamali",
    author: "Emmanuel Akyoo",
    category: "Familia",
    price: 25000,
    originalPrice: 31000,
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=400&h=600&fit=crop",
    rating: 4.5,
    reviews: 134,
    pages: 210,
    publishedYear: 2023,
    inStock: true,
    stockCount: 16,
    description: "Mafundisho ya jinsi ya kuwa mzazi mzuri na mjasiriamali mwenye mafanikio.",
    featured: false,
    bestseller: false,
    newArrival: false
  },
  {
    id: 9,
    title: "Uwezekano Hauishiki",
    author: "Emmanuel Akyoo",
    category: "Inspirational",
    price: 28000,
    originalPrice: 34000,
    image: "https://images.unsplash.com/photo-1509266272358-7701da638078?w=400&h=600&fit=crop",
    rating: 4.6,
    reviews: 89,
    pages: 275,
    publishedYear: 2022,
    inStock: true,
    stockCount: 14,
    description: "Jinsi ya kubadilisha mtazamo wako na kuona uwezekano katika kila hali.",
    featured: true,
    bestseller: false,
    newArrival: false
  },
  {
    id: 10,
    title: "Hatua za Mafanikio",
    author: "Emmanuel Akyoo",
    category: "Mafanikio",
    price: 38000,
    originalPrice: 45000,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop",
    rating: 4.9,
    reviews: 211,
    pages: 340,
    publishedYear: 2024,
    inStock: true,
    stockCount: 9,
    description: "Mbinu za kufuata ili kufikia mafanikio makubwa katika maisha na biashara.",
    featured: true,
    bestseller: true,
    newArrival: true
  }
];